package app.gui.actividades;

import app.logic.Usuario;
import javax.swing.JPanel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

public class ActividadesPanel extends javax.swing.JPanel {

    Usuario usuario = null;
    int mostrando = 0;

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    String etapa;

    /**
     * Creates new form inicioPanel
     *
     * @param usuario
     */
    public ActividadesPanel(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        etapa = usuario.getEtapaUsuario();
        mostrando = usuario.getEtapa();
        etapaLabel.setText(etapa);
        if (mostrando == 1) {
            // Muestra un panel en el panel contenido
            ActividadesLevesPanel acLeves = new ActividadesLevesPanel(usuario);
            showPanel(acLeves);
            jButton4.setText("Mostrar actividades de la etapa Moderada");
        } else if (mostrando == 0) {
            // Muestra un panel en el panel contenido
            ActividadesModeradasPanel acModeradas = new ActividadesModeradasPanel(usuario);
            jButton4.setText("Mostrar actividades de la etapa Leve");
            showPanel(acModeradas);
        } else {
            // Muestra un panel en el panel contenido
            ActividadesAvanzadasPanel acAvanzadas = new ActividadesAvanzadasPanel(usuario);
            jButton4.setText("Mostrar actividades de la etapa Avanzada");
            showPanel(acAvanzadas);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txt1 = new javax.swing.JLabel();
        etapaLabel = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        contActv = new javax.swing.JPanel();
        fondoLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(81, 3, 113));
        jPanel1.setForeground(new java.awt.Color(255, 153, 153));

        txt1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt1.setForeground(new java.awt.Color(255, 255, 255));
        txt1.setText("Actividades sugeridas para la etapa");

        etapaLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        etapaLabel.setForeground(new java.awt.Color(0, 153, 153));
        etapaLabel.setText("--------");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(txt1)
                .addGap(34, 34, 34)
                .addComponent(etapaLabel)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt1)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(etapaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, 60));

        jButton4.setBackground(new java.awt.Color(0, 255, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setText("Mostrar actividades de la etapa Moderada");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        bg.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, -1, 40));

        contActv.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout contActvLayout = new javax.swing.GroupLayout(contActv);
        contActv.setLayout(contActvLayout);
        contActvLayout.setHorizontalGroup(
            contActvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );
        contActvLayout.setVerticalGroup(
            contActvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        bg.add(contActv, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 620, 390));

        fondoLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fondoLabel.setForeground(new java.awt.Color(51, 51, 51));
        fondoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/backgroundMain.jpg"))); // NOI18N
        bg.add(fondoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 660));

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (mostrando == 1) {
            // Muestra un panel en el panel contenido
            ActividadesLevesPanel acLeves = new ActividadesLevesPanel(usuario);
            showPanel(acLeves);
            jButton4.setText("Mostrar actividades de la etapa Moderada");
            etapaLabel.setText("Leve");
            mostrando = 0;
        } else {
            // Muestra un panel en el panel contenido
            ActividadesModeradasPanel acModeradas = new ActividadesModeradasPanel(usuario);
            showPanel(acModeradas);
            jButton4.setText("Mostrar actividades de la etapa Leve");
            etapaLabel.setText("Moderada");
            mostrando = 1;
        }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel contActv;
    private javax.swing.JLabel etapaLabel;
    private javax.swing.JLabel fondoLabel;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt1;
    // End of variables declaration//GEN-END:variables

    private void showPanel(JPanel p) {
        p.setSize(700, 660);
        contActv.removeAll();
        contActv.add(p, new AbsoluteConstraints(0, 0, -1, -1));
        contActv.revalidate();
        contActv.repaint();
    }
}
