package app.gui.inicio;

import app.logic.Main;
import app.logic.Usuario;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;

public final class EtapaSeleccion extends javax.swing.JFrame {

    private Usuario usuario = new Usuario();
    // Atributo de lista
    private static List<Usuario> usuarios;

    public EtapaSeleccion(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BrainUP - Etapa");
        setResizable(false);

        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 153, 102));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("AVANZADA");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        content.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, 220, 130));

        jButton2.setBackground(new java.awt.Color(255, 255, 102));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("LEVE");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        content.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 220, 130));

        jButton3.setBackground(new java.awt.Color(153, 255, 102));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("MODERADA");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        content.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 220, 130));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Seleccione la etapa de la enfermedad que considere");
        content.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        content.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 800, 10));

        jScrollPane2.setBackground(new java.awt.Color(204, 153, 255));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 255, 153));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea2.setRows(5);
        jTextArea2.setText("En la etapa temprana del Alzheimer,  la persona puede desenvolverse de forma\nindependiente. Es posible que pueda conducir, trabajar y participar de actividades \nsociales.  A pesar de esto, la persona puede sentir que tiene episodios de pérdida \nde memoria que incluyen olvidarse palabras familiares o la ubicación de objetos \ncotidianos.");
        jScrollPane2.setViewportView(jTextArea2);

        content.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 620, 130));

        jScrollPane1.setBackground(new java.awt.Color(204, 153, 255));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(153, 255, 153));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea1.setRows(5);
        jTextArea1.setText("Es posible que note que la persona:\nConfunda palabras, se frustra o enoja.\nActúa de forma inesperada.\nPuede dificultar la expresión de \npensamientos.");
        jScrollPane1.setViewportView(jTextArea1);

        content.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 620, 130));

        jScrollPane3.setBackground(new java.awt.Color(204, 153, 255));

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(255, 153, 153));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(51, 51, 51));
        jTextArea3.setRows(5);
        jTextArea3.setText("La persona pierde la capacidad de responder a su entorno y de controlar\nlos movimientos. Aunque pueden decir palabras o frases, es posible que\nocurran cambios significativos en la personalidad.\n");
        jScrollPane3.setViewportView(jTextArea3);

        content.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 620, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/goback.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        content.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, -1, 90));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/backgroundMain.jpg"))); // NOI18N
        content.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MainScreen main;
        if (guardarUsuario(0)) {
            usuario.setEtapa(0);
            Main.setConectado(Main.conectarBaseDatos());
            main = new MainScreen(usuario);
            this.setVisible(false);
            main.setVisible(true);
            main.setUsuario(usuario);
            main.setLocationRelativeTo(null);

            System.out.println("Guardado correctamente");
        } else {
            System.out.println("Ha ocurrido algun error");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        MainScreen main;
        if (guardarUsuario(1)) {
            usuario.setEtapa(1);
            Main.setConectado(Main.conectarBaseDatos());
            main = new MainScreen(usuario);
            this.setVisible(false);
            main.setVisible(true);
            main.setUsuario(usuario);
            main.setLocationRelativeTo(null);
            Main.setConectado(Main.conectarBaseDatos());
            System.out.println("Guardado correctamente");
        } else {
            System.out.println("Ha ocurrido algun error");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainScreen main;

        if (guardarUsuario(2)) {
            usuario.setEtapa(2);
            Main.setConectado(Main.conectarBaseDatos());
            main = new MainScreen(usuario);
            this.setVisible(false);
            main.setVisible(true);
            main.setUsuario(usuario);
            main.setLocationRelativeTo(null);

            System.out.println("Guardado correctamente");
        } else {
            System.out.println("Ha ocurrido algun error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        RegistroUsuario registro = new RegistroUsuario(usuarios);
        this.setVisible(false);
        registro.setVisible(true);
        registro.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel2MouseClicked

    private boolean guardarUsuario(int etapa) {
        boolean conectado = Main.crearBaseDatos();
        if (conectado) {
            // En el la tabla usuario de la base de datos registra los datos
            try {
                String nombre = usuario.getNombre();
                String apellido = usuario.getApellido();
                int avatar = usuario.getAvatar();
                int dia = usuario.getFechaNacimiento().getDia();
                int mes = usuario.getFechaNacimiento().getMes();
                int anio = usuario.getFechaNacimiento().getAnio();
                String cedula = usuario.getCedula();

                String SQL = "INSERT INTO usuario (cedula, nombre, apellido, avatar, dianac, mesnac, anionac, etapa) VALUES ('" + cedula + "','" + nombre + "', '" + apellido + "', '" + avatar + "', '" + dia + "', '" + mes + "', '" + anio + "', '" + etapa + "')";
                PreparedStatement st = Main.getConnect().prepareStatement(SQL);
                st.executeUpdate();
                return true;

            } catch (SQLException ex) {
                // En caso de que no se pueda guardar el usuario elimina la base de datos creada
                Main.eliminarDataBase();
                JOptionPane.showMessageDialog(null, "Error, intente nuevamente");

                // Termina el programa
                System.exit(0);
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo conectar a la base de datos");
        }
        return false;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel content;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables

}
