package app.gui.inicio;

import app.logic.Usuario;

import javax.swing.JOptionPane;
import java.util.List;

public class InicioForm extends javax.swing.JFrame {

    // Atributo de lista
    private static List<Usuario> usuarios;

    public List<Usuario> getUsuarios() {
        return usuarios;
    }

    public void setUsuarios(List<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

    /**
     * Creates new form InicioForm
     *
     * @param usuarios
     */
    public InicioForm(List<Usuario> usuarios) {
        initComponents();
        InicioForm.usuarios = usuarios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mensaje1 = new javax.swing.JLabel();
        registrarButton = new javax.swing.JButton();
        entrarButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cedulaTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Entrar");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mensaje1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        mensaje1.setForeground(new java.awt.Color(0, 0, 0));
        mensaje1.setText("Iniciar Sesión");
        jPanel1.add(mensaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 170, 40));

        registrarButton.setBackground(new java.awt.Color(255, 51, 204));
        registrarButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        registrarButton.setForeground(new java.awt.Color(255, 255, 255));
        registrarButton.setText("REGISTRAR");
        registrarButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        registrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(registrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 340, 40));

        entrarButton.setBackground(new java.awt.Color(0, 204, 204));
        entrarButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        entrarButton.setForeground(new java.awt.Color(255, 255, 255));
        entrarButton.setText("ENTRAR");
        entrarButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        entrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(entrarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 340, 50));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 340, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Ingrese su número de cédula");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 30));

        cedulaTxt.setBackground(new java.awt.Color(51, 51, 51));
        cedulaTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cedulaTxt.setForeground(new java.awt.Color(255, 255, 255));
        cedulaTxt.setBorder(null);
        cedulaTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cedulaTxt.setOpaque(true);
        cedulaTxt.setSelectedTextColor(new java.awt.Color(153, 153, 153));
        cedulaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaTxtActionPerformed(evt);
            }
        });
        jPanel1.add(cedulaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 340, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 340, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 430, 20));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/backgroundSignUp.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -240, 500, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarButtonActionPerformed

        String cedula = cedulaTxt.getText();
        if (cedula.length() > 0) {
            if (validarCedula(cedula)) {
                // Busca en la lista de usuarios un match en cedula
                usuarios.forEach(usuario -> {
                    if (usuario.getCedula().equals(cedula)) {
                        MainScreen main = new MainScreen(usuario);
                        main.setVisible(true);
                        main.setLocationRelativeTo(null);
                        this.setVisible(false);

                    } else {
                        jLabel3.setText("No encontrado, intente nuevamente");
                    }
                });
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese un número de cédula");
        }


    }//GEN-LAST:event_entrarButtonActionPerformed

    private void registrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarButtonActionPerformed

        RegistroUsuario registro = new RegistroUsuario(usuarios);
        this.setVisible(false);
        registro.setVisible(true);
        registro.setLocationRelativeTo(null);
    }//GEN-LAST:event_registrarButtonActionPerformed

    private void cedulaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaTxtActionPerformed
        // TODO add your handling code here:
        cedulaTxt.setText("");
    }//GEN-LAST:event_cedulaTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioForm(usuarios).setVisible(true);
            }
        });
    }

    private boolean validarCedula(String cedula) {
        // Verifica que la cedula sea valida
        // Verifica que solamente hayan digitos en el string cedula
        if (cedula.matches("[0-9]+")) {
            // Verifica que el string tenga 10 digitos
            if (cedula.length() == 10) {
                // Verifica que la suma de los 2 primeros digitos esten entre 1 y 24
                if (Integer.parseInt(cedula.substring(0, 2)) >= 1 && Integer.parseInt(cedula.substring(0, 2)) <= 24) {
                    //Verifica que el tercer digito esten entre 0 y 6
                    if (Integer.parseInt(cedula.substring(2, 3)) >= 0 && Integer.parseInt(cedula.substring(2, 3)) <= 6) {
                        return true;
                    } else {
                        JOptionPane.showMessageDialog(null, "Cédula inválida");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Cédula fuera de rango");
                    return false;
                }
            } else {
                JOptionPane.showMessageDialog(null, "Cédula debe constar de 10 dígitos");
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Cédula inválida. Ingrese solamente dígitos");
            return false;
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField cedulaTxt;
    private javax.swing.JButton entrarButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel mensaje1;
    private javax.swing.JButton registrarButton;
    // End of variables declaration//GEN-END:variables
}
