package app.gui.inicio;

import app.logic.Fecha;
import app.logic.Main;
import app.logic.Usuario;

public class InicioPanel extends javax.swing.JPanel {

    Fecha actual;
    Usuario usuario = null;

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    /**
     * Creates new form inicioPanel
     * @param usuario
     */
    public InicioPanel(Usuario usuario) {
        initComponents();
        actual = new Fecha();
        actualizarFecha(actual);
        this.usuario = usuario;
        setInformation();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        fechaLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        estadoSQL = new javax.swing.JLabel();
        estadoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(81, 3, 113));
        jPanel1.setForeground(new java.awt.Color(255, 153, 153));

        fechaLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        fechaLabel.setForeground(new java.awt.Color(255, 255, 255));
        fechaLabel.setText("El día de hoy es -- de -- del año --");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(fechaLabel)
                .addContainerGap(298, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(fechaLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, 60));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 153));
        jLabel2.setText("Bienvenido :)");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        estadoSQL.setBackground(new java.awt.Color(0, 0, 0));
        estadoSQL.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        estadoSQL.setForeground(new java.awt.Color(0, 153, 0));
        estadoSQL.setText("---");
        bg.add(estadoSQL, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, -1, -1));

        estadoLabel.setBackground(new java.awt.Color(0, 0, 0));
        estadoLabel.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        estadoLabel.setForeground(new java.awt.Color(0, 0, 0));
        estadoLabel.setText("Estado de la conexión:");
        bg.add(estadoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/backgroundMain.jpg"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 660));

        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 660));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JLabel estadoSQL;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void actualizarFecha(Fecha actual) {
        fechaLabel.setText("Hoy es " + actual.getDia() + " de " + actual.getMesString() + " del año " + actual.getAnio() + " ");
    }

    public void setInformation() {
        try {
            jLabel2.setText("Bienvenido " + usuario.getNombre() + " :)");

            if (!(Main.isConectado())) {
                estadoSQL.setText("desconectado");
                estadoSQL.setForeground(new java.awt.Color(255, 51, 51));
            } else {
                estadoSQL.setText("conectado");
                estadoSQL.setForeground(new java.awt.Color(0, 153, 0));

            }

        } catch (NullPointerException npe) {
            jLabel2.setText("Hola  usuario");
        } catch (Exception e) {
            jLabel2.setText("Problema al encontrar usuario");
        }
    }
}
